project_id = "yzuhtwkzvosibqpzlgtq"

[functions.select-papers]
verify_jwt = false

[functions.batch-select-papers]
verify_jwt = false

[functions.generate-blog-post]
verify_jwt = false

[functions.publish-blog-post]
verify_jwt = false

[functions.send-newsletter]
verify_jwt = false